CREATE DATABASE IF NOT EXISTS electric_vehicles;
USE electric_vehicles;

CREATE TABLE IF NOT EXISTS company (
	companyID INT NOT NULL AUTO_INCREMENT,
	company VARCHAR(255),
	PRIMARY KEY (companyID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicleType (
	vehicleTypeID INT NOT NULL AUTO_INCREMENT,
	vehicleType VARCHAR(255),
	PRIMARY KEY (vehicleTypeID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS brand (
	brandID INT NOT NULL AUTO_INCREMENT,
	brand VARCHAR(255),
	PRIMARY KEY (brandID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS typ (
	typID INT NOT NULL AUTO_INCREMENT,
	typ VARCHAR(255),
	PRIMARY KEY (typID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS chargingStation (
	chargingStationID INT NOT NULL AUTO_INCREMENT,
	chargingStation VARCHAR(255),
	PRIMARY KEY (chargingStationID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle (
	vehicleID INT NOT NULL AUTO_INCREMENT,
	modell VARCHAR(255),
	chargingRate DOUBLE,
	totalRange VARCHAR(255),
	batteryRange VARCHAR(255),
	acceleration VARCHAR(255),
	maxSpeed DOUBLE,
	companyID INT NOT NULL,
	vehicleTypeID INT NOT NULL,
	brandID INT NOT NULL,
	typID INT NOT NULL,
	chargingStationID INT NOT NULL,
	PRIMARY KEY (vehicleID),
	CONSTRAINT fk_companyID FOREIGN KEY (companyID) REFERENCES company(companyID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT fk_vehicleTypeID FOREIGN KEY (vehicleTypeID) REFERENCES vehicleType(vehicleTypeID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT fk_brandID FOREIGN KEY (brandID) REFERENCES brand(brandID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT fk_typID FOREIGN KEY (typID) REFERENCES typ(typID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT fk_chargingStationID FOREIGN KEY (chargingStationID) REFERENCES chargingStation(chargingStationID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS batteryType (
	batteryTypeID INT NOT NULL AUTO_INCREMENT,
	batteryType VARCHAR(255),
	PRIMARY KEY (batteryTypeID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS battery (
	batteryID INT NOT NULL AUTO_INCREMENT,
	batteryCapacity DOUBLE,
	chargingTime VARCHAR(255),
	batteryTypeID INT NOT NULL,
	PRIMARY KEY (batteryID),
	CONSTRAINT fk_batteryTypeID FOREIGN KEY (batteryTypeID) REFERENCES batteryType(batteryTypeID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_battery (
	vehicleID INT NOT NULL,
	batteryID INT NOT NULL,
	PRIMARY KEY (vehicleID, batteryID),
	CONSTRAINT fk_vehicleID FOREIGN KEY (vehicleID) REFERENCES vehicle(vehicleID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT fk_batteryID FOREIGN KEY (batteryID) REFERENCES battery(batteryID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS country (
	countryID INT NOT NULL AUTO_INCREMENT,
	country VARCHAR(255),
	PRIMARY KEY (countryID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_country (
	vehicleID INT NOT NULL,
	countryID INT NOT NULL,
	PRIMARY KEY (vehicleID, countryID),
	CONSTRAINT fk_vehicleID FOREIGN KEY (vehicleID) REFERENCES vehicle(vehicleID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE,
	CONSTRAINT fk_countryID FOREIGN KEY (countryID) REFERENCES country(countryID)
		ON DELETE NO ACTION
		ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
